services:
  - type: web
    name: maxbooster
    env: node
    installCommand: npm install --include=dev
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

